name = "深巷世界"
author = "深巷世界维护组"
version = "1.2.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d51eed9589bf6f5caf1ff031dc2567b7393aa06b76562c5375bef176fe59bed1"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
