name = "深巷世界-测试服"
author = "深巷世界维护组"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88ca2366fbb616f2aac59f8afa08556c26588ecda22113b5e746b5ef35d27da6"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
